### ISSUE TITLE
TimeZone and Cron Execute issues

### ISSUE THREAD

**Issue by aegie** [linuxserver/docker-webgrabplus#20]
Hello,

I'd like to report 2 bugs I found that apply to my setup.
First (this took me a long time to troubleshoot), after the wg-cron file is modified (setting up the time to execute the job), permissions are changed and the execute rights from owner is dropped.
You need to re apply in order for the cron job to work.

Second, even though I pass the TZ in my docker compose, my container timezone is wrong and I need to to use `/etc/timezone:/etc/timezone:ro` to correct it. The time is correct, but due to the wrong time zone, cron jobs have, in my case, a 2 hour difference (timezone is Etc/UTC vs my current TZ Europe/Bucharest).

I found this bug also in other containers
![11](https://user-images.githubusercontent.com/30295068/72480389-f54eed00-37ff-11ea-95df-41c4de9a390f.jpg)

I am running docker on openmediavault 4 with linux kernel 4.19

```
---
version: "2"
services:
  webgrabplus:
    image: linuxserver/webgrabplus
    container_name: webgrabplus
    environment:
      - TZ=Europe/Bucharest #this doesn't seem to function correctly
      - PUID=1001
      - PGID=100
    volumes:
      - /sharedfolders/mediatools/webgrabplus:/config
      - /sharedfolders/mediatools/xteve/data:/data
      - /etc/timezone:/etc/timezone:ro #needed to correct the issue
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
     - media
```
